### ISSUE TITLE
subcomment display

### ISSUE THREAD

**Issue by alessapm** [alessapm/remote_read#2]
When I try to post a subcomment I get this message: 

error: invalid input syntax for integer: "undefined"

the error is in my subcomments under my controller.show, and my subcomments object is coming back as []. The subcomments are also loading into my database without comment_id or post_id. 

I've tried tracing back my route, which is all working, and reconfiguring my database to make sure its loading the right datatype for each cell. 

@gittheking

**Comment by gittheking** [comment]
@alessapm As of right now your creating your comment with:
```javascript
Subcomment.create(req.body.sub)
```
So, you're assuming that post_id and comment_id are both in `req.body.sub`, however if we look at the form in your `views/books/show` we can see that the post_id and comment_id are not part of the form body:
```
<form method="POST" action="/subcomments">
  <h5>Reply to Comment</h5>
  <label for="username">Name for reply:</label><br>
  <input type="text" name="sub[username]"><br>
  <label for="reply">Reply:</label><br>
  <input class = 'reply-field' type="text" name="sub[reply]"><br>
  <input class = 'submit-reply' type="submit" value="submit">
</form>
```
If you'd like to pass those values you'll have to include them in your form somewhere (without being shown) - read this article on passing hidden field values in forms http://www.echoecho.com/htmlforms07.htm

**Comment by gittheking** [comment]
@alessapm Hey, can you close this now that it has been resolved? Thanks!
