### ISSUE TITLE
subcomment display, part II

### ISSUE THREAD

**Issue by alessapm** [alessapm/remote_read#3]
I can only get my subcomments to display on all comments for a given post. 

For example, if Post 1 has 4 comments and I write a subcomment for the first comment, the subcomment then displays under all 4 comments. 

There is no error message or anything, just a display in the wrong places. 

I've tried using a conditional statement in my EJS, equating to 

<% sub.forEach((subeach) => { %>
                      **## <% if (subeach.comment_id === each.id) { %>**
                      <div class='comment-beta'>
                        <h5> <%= subeach.username %></h5>
                        <p class ='italic'> <%= subeach.reply %></p>
                      </div>
                      <% } %>
       <% }) %>

which should match the comment_id of the subcomment to the id of the comment, but that apparently doesnt work. 

I also tried reading into json_agg, but confused myself more than anything else. 

@gittheking @irwintsay @arun-instructor

**Comment by gittheking** [comment]
@alessapm 
So, this may not be the most elegant way to solve your problem,  but I think doing this could fix what you're looking for:
- In your `books/controller.js`'s `show` method, you can filter the data _before_ you send it to the view like:

```javascript
thesecomments.forEach((comment) => {
  comment.subcomments = subcomments.filter(sub => sub.comment_id === comment.id);
});
res.render('books/show', { books: data, comments: thesecomments});
```
which would give each of your comment objects their own array of subcomment objects.

Let me know if that works!
